version: '3.0'
services:
  web:
    ports:
      - "80:5000"
    depends_on:
      - redis
    volumes:
      - .:/code
    environment:
      FLASK_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: redis:6.0-rc3
    volumes:
      - "redis-data:/data"
volumes:
  redis-data: